import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Container from "@/components/global/container";
import NavBar from "@/components/global/navbar";
import Footer from "@/components/global/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Big Boss Digital Marketplace",
  description: "Generated by Aaron K. Altman | Big Boss Enterprises",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <NavBar />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
